DROP TABLE IF EXISTS groups CASCADE;
CREATE TABLE groups (
id INT PRIMARY KEY,
groupName VARCHAR NOT NULL
);

DROP TABLE IF EXISTS teacher CASCADE;
CREATE TABLE teacher (
id INT PRIMARY KEY,
firstName VARCHAR NOT NULL,
lastName VARCHAR NOT NULL
);

DROP TABLE IF EXISTS student CASCADE;
CREATE TABLE student (
id INT PRIMARY KEY,
firstName VARCHAR NOT NULL,
lastName VARCHAR NOT NULL,
group_id INT,

FOREIGN KEY (group_id) REFERENCES groups(id)
);

DROP TABLE IF EXISTS lecture CASCADE;
CREATE TABLE lecture (
id INT PRIMARY KEY,
lectureName VARCHAR NOT NULL,
description VARCHAR NOT NULL,
teacher_id INT,
group_id INT,

FOREIGN KEY (teacher_id) REFERENCES teacher(id),
FOREIGN KEY (group_id) REFERENCES groups(id)
);